# Generated by Django 4.0.4 on 2022-07-26 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Analises', '0008_alter_amostra_horario_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 20, 44, 3, 169946)),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analises.nomeamostra'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='ph_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analises.ph'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='temperatura_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analises.temperatura'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='usuario_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
