# Generated by Django 4.0.4 on 2022-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0012_alter_amostra_horario_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ph',
            name='horario_dia',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='horario_dia',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
