# Generated by Django 4.0.4 on 2022-08-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analises', '0013_alter_ph_horario_dia_alter_temperatura_horario_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amostra',
            old_name='primeira_etapa',
            new_name='etapa_boca',
        ),
    ]
