# Generated by Django 4.0.4 on 2022-07-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_aluno_options_alter_pessoa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='test', max_length=255, unique=True, verbose_name='E-mail'),
        ),
    ]
