# Generated by Django 4.0.4 on 2022-07-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_pessoa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
