# Generated by Django 4.0.4 on 2022-07-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_pessoa_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='username',
            field=models.CharField(default='test', max_length=255, unique=True, verbose_name='Usuario'),
        ),
    ]
