# Generated by Django 4.0.4 on 2022-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
