# Generated by Django 4.0.4 on 2022-06-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telacadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telacadastro.pessoa')),
                ('ra', models.CharField(max_length=150)),
            ],
            bases=('telacadastro.pessoa',),
        ),
    ]
