# Generated by Django 4.0.4 on 2022-07-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telacadastro', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telacadastro.pessoa')),
                ('siape', models.CharField(max_length=7, verbose_name='SIAPE')),
            ],
            bases=('telacadastro.pessoa',),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=150, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=150, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=50, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='usuario',
            field=models.CharField(max_length=150, verbose_name='Usuário'),
        ),
    ]
